=encoding utf8

=head1 The Perl 6 summary for the weeks of 2006-02-13 through 2006-02-28

=head2 Summary updates

Starting with this update, Ann Barcomb will be writing the Perl 6 
summaries.  Her plan is to release new issues on Sundays, initially
dealing with the backlog at a rate of one month per week, and eventually
returning to posting a summary of the previous week on a weekly basis.

The proposed schedule is:

=over 4

=item * July 9th: February (from 13th)

=item * July 16th: March

=item * July 23th: April

=item * July 30th: May

=item * August 6th: June

=item * August 13th: July

=item * August 20th: August (till 19th)

=item * August 27th: Resume normal schedule

=back

=head2 Compiler (perl6-compiler)

=head3 Making Pugs aware of Parrot

Peter Schwenn requested a concrete example settings to make Pugs aware of
Parrot.  Beau Cox replied with step-by-step instructions.

L<http://xrl.us/oxoa>

=head3 Difficulty installing Pugs on Cygwin

Syed Uzair Aqeel reported a Cygwin problem with finding package plugins
when creating a makefile.  Audrey made a suggestion.

L<http://xrl.us/oxob>

=head3 Installation failure of Pugs revisions 9188 and 9204

Beau Cox reported that the 9188 revision of Pugs failed to pass smoke tests
and install, and that the problem persisted with Pugs 9204 even 
after a reinstall of ghc and Haskell.  Beau wrote a makefile patch, which
also worked for chromatic, who had experienced the same problem.

L<http://xrl.us/oxoc>

=head2 Internals (parrot-porters)

Please see L<02-28-parrot.pod>.

=head2 Language (perl6-language)

=head3 Typo Alert: Synopsis 5 

Amos Robinson found a typo and Luke Palmer promptly corrected it.

L<http://xrl.us/oxxb>

=head3 Implementation of :w in regexes and other regex questions 

David Romano asked some questions on extending the Rules domain specific
language, the semantics of whitespace skipping, and negated matching
semantics.  Luke Palmer replied and explained that the extensions were not
yet specified, and recommend possible solutions to the other two questions.
Discussion ensued.

L<http://xrl.us/oxxc>

=head3 Overloading the variable declaration process 

Darren Duncan wondered if he could get default values in variables instead
of undef, in order to avoid calling the constructor, by simply annotating
the type of the variable.  Audrey Tang explained that a similar construct
is available.  This was followed by a discussion on the subject of class
prototypes as default values for typed variables, as well as philosophical
issues.

L<http://xrl.us/oxxd>

=head3 Instance attributes collision 

Yiyi Hu asked what happens when different sigil attributes with the same
name are declared in a single class.  Various participants debated the merits
of errors versus warnings.

L<http://xrl.us/oxxe>

=head3 C<CODE {...}> mentioning variables without interpolation

Brad Bowman asked about the semantics of quasiquoting and variable 
interpolation for Perl 6's Macro language.  Larry Wall explained the
semantics of AST binding, the caller's scope, interpolating ASTs into
the macro, and the C<COMPILING::> variable prefix.  This was followed by
a comment on Brad's signature about intelligence and good sense.

L<http://xrl.us/oxxf>

=head3 Selective String Interpolation 

Brad Bowman wanted to know if string interpolation and escaping could be
optimized for creating strings of Perl code that selectively interpolate.
Ideally he would be able to declare which variables are interpolated.  He
also mentioned closure interpolation and how it does not work well when 
quoting strings of code.  Many people provided ideas, covering Lisp and
Ruby, backslashes, and custom quote operators.

L<http://xrl.us/oxxg>

=head3 Some newbie questions about Synopsis 5

H. Stelling asked about Rule capture numbering, aliasing semantics, and
nested subpattern details.  Patrick R. Michaud clarified and the capture
numbering scheme was discussed.

L<http://xrl.us/oxxh>

=head3 Named Subroutine return values

Joe Gottman wanted to know if subroutine declarations without an explicit
declaration type (C<my>, C<our>) can be annotated with a return value type.
Damian Conway replied that the C<returns> trait can used regardless of the
declaration syntax.  Luke Palmer and Larry Wall discussed the exact 
semantics of C<our Type sub foo>, C<< --> >> and C<returns> style return
type declarations.

L<http://xrl.us/oxxi>

=head3 S02: Reserved namespace ops 

TSa asked what reservations the design team had about the various uses of
the reserved syntax for type subscripting.  Larry Wall reserved his right to
silence, adding that he thought that C<is reserved> means "we don't have
the foggiest idea what we'll do with this, but we have a suspicion that
if we let people use this particular thing right now, we'll regret it 
someday."  The official status of the various items in the F<notes/> 
directory was clarified -- they are considered to be unofficial.

L<http://xrl.us/oxxj>

=head3 Synopsis 29 patch

Larry Wall posted a patch for Synopsis 29, recognizing it as official.
Ruud H.G. van Tol followed up with questions about a round function,
and pi/atan/atan2.

L<http://xrl.us/oxxk>

=head3 Synopsis 29 and Complex numbers 

Jonathan Lang noted that Synopsis 29 deals with complex numbers when
describing the sqrt function, but omitted others.  He proceeded to
list the functions which require special handling of complex numbers.
Several people commented.

L<http://xrl.us/oxxm>

=head2 Acknowledgments

chromatic recruited me at YAPC::NA 2006, and Jesse Vincent
proposed this task.  Audrey Tang helped me to get started and
reviewed this summary, and Yuval Kogman assisted with the Language
section.

If you appreciate Perl, consider contributing to the Perl Foundation to
help support the development of Perl.

L<http://donate.perlfoundation.org/>

Comments on the summary can be sent to C<kudra@domaintje.com>.

=head2 See also

=over 4

=item * Perl Foundation activities

L<http://blog.perlfoundation.org/>

=item * Perl 6 Development

L<http://dev.perl.org/perl6>

=item * Planet Perl Six

L<http://planetsix.perl.org/>

=back

