=encoding utf8

=head1 The Perl 6 summary for the month of 2006-04

=head Summary updates

=head2 Users (perl6-users)

=head2 Compiler (perl6-compiler)

=head2 Parrot-Porters (parrot-porters, formerly perl6-internals)

The parrot-porters list was called perl6-internals during the period 
covered by this summary.

=head2 Language (perl6-language)

=head2 Acknowledgments

If you appreciate Perl, consider 
L<http://donate.perlfoundation.org|contributing to the Perl Foundation>
to help support the development of Perl.

Thank you to everyone who has pointed out mistakes and offered suggestions
for improving this series.  Comments on this summary can be sent to 
Ann Barcomb, kudra@domaintje.com.

=head2 See also

=over 4

=item * L<http://blog.perlfoundation.org|Perl Foundation activities>

=item * L<http://dev.perl.org/perl6|Perl 6 Development>

=item * L<http://planetsix.perl.org/perl6|Planet Perl Six>

=back