=encoding utf8

=head1 The Perl 6 summary for the weeks of 2006-06-01 through 2006-06-30

=head2 Compiler (perl6-compiler)

=head2 Internals (perl6-internals)

=head2 Language (perl6-language)

=head2 See also

=over 4

=item * Perl Foundation activities

L<http://blog.perlfoundation.org/>

=item * Perl 6 Development

L<http://dev.perl.org/perl6>

=item * Planet Perl Six

L<http://planetsix.perl.org/>

=back

