#!/usr/bin/perl
use v5.10;
my %methods;
while (<>) {
    if (/^\[SMOP_MOLD_DEBUG\] 0x\S+ eval "(.*)" on "(.*)"\.$/) {
        $methods{"$2.$1"}++;
    }
}
for (sort {$methods{$b} <=> $methods{$a}} keys %methods) {
    say "$_ = ",$methods{$_};
}
