{

    package Hash;

    # Do not edit this file - Perl 5 generated by KindaPerl6
    use v5;
    use strict;
    no strict 'vars';
    use KindaPerl6::Runtime::Perl5::Runtime;
    my $_MODIFIED;
    BEGIN { $_MODIFIED = {} }

    BEGIN {
        $_ =
          ::DISPATCH( $::Scalar, "new",
            { modified => $_MODIFIED, name => "$_" } );
    }
    $::Hash =
      ::DISPATCH(
        ::DISPATCH( $::Class, 'new', ::DISPATCH( $::Str, 'new', 'Hash' ) ),
        'PROTOTYPE', );
    ::DISPATCH(
        ::DISPATCH( $::Hash, 'HOW', ),
        'add_parent',
        ::DISPATCH( $::Str, 'new', 'Container' )
    );
    ::DISPATCH(
        ::DISPATCH( $::Hash, 'HOW', ),
        'add_attribute',
        ::DISPATCH( $::Str, 'new', 'pairs' )
    );
    ::DISPATCH(
        ::DISPATCH( $::Hash, 'HOW', ),
        'add_method',
        ::DISPATCH( $::Str, 'new', 'perl' ),
        ::DISPATCH(
            $::Method,
            'new',
            sub {
                my $self   = shift;
                my $List__ = \@_;
                ::DISPATCH( $::Str, 'new', '{ ... }' );
            }
        )
    );
    ::DISPATCH(
        ::DISPATCH( $::Hash, 'HOW', ),
        'add_method',
        ::DISPATCH( $::Str, 'new', 'str' ),
        ::DISPATCH(
            $::Method,
            'new',
            sub {
                my $self   = shift;
                my $List__ = \@_;
                ::DISPATCH( $::Str, 'new', '...' );
            }
        )
    );
    ::DISPATCH(
        ::DISPATCH( $::Hash, 'HOW', ),
        'add_method',
        ::DISPATCH( $::Str, 'new', 'true' ),
        ::DISPATCH(
            $::Method,
            'new',
            sub {
                my $self   = shift;
                my $List__ = \@_;
                ::DISPATCH( $GLOBAL::Code_true, 'APPLY', );
            }
        )
    );
    1
}

