{

    package Multi;

    # Do not edit this file - Perl 5 generated by KindaPerl6
    use v5;
    use strict;
    no strict 'vars';
    use KindaPerl6::Runtime::Perl5::Runtime;
    my $_MODIFIED;
    BEGIN { $_MODIFIED = {} }

    BEGIN {
        $_ =
          ::DISPATCH( $::Scalar, "new",
            { modified => $_MODIFIED, name => "$_" } );
    }
    do {
        if (
            ::DISPATCH(
                ::DISPATCH(
                    ::DISPATCH( $GLOBAL::Code_VAR_defined, 'APPLY', $::Multi ),
                    "true"
                ),
                "p5landish"
            )
          )
        {
        }
        else {
            do {
                ::MODIFIED($::Multi);
                $::Multi = ::DISPATCH(
                    ::DISPATCH(
                        $::Class, 'new',
                        ::DISPATCH( $::Str, 'new', 'Multi' )
                    ),
                    'PROTOTYPE',
                );
              }
        }
    };
    ::DISPATCH(
        ::DISPATCH( $::Multi, 'HOW', ),
        'add_parent',
        ::DISPATCH( $::Str, 'new', 'Code' )
    );
    ::DISPATCH(
        ::DISPATCH( $::Multi, 'HOW', ),
        'add_attribute',
        ::DISPATCH( $::Str, 'new', 'long_names' )
    );
    ::DISPATCH(
        ::DISPATCH( $::Multi, 'HOW', ),
        'add_method',
        ::DISPATCH( $::Str, 'new', 'APPLY' ),
        ::DISPATCH(
            $::Method,
            'new',
            sub {
                my $candidates;
                $candidates =
                  ::DISPATCH( $::Scalar, 'new',
                    { modified => $_MODIFIED, name => '$candidates' } )
                  unless defined $candidates;

                BEGIN {
                    $candidates =
                      ::DISPATCH( $::Scalar, 'new',
                        { modified => $_MODIFIED, name => '$candidates' } );
                }
                my $sub;
                $sub =
                  ::DISPATCH( $::Scalar, 'new',
                    { modified => $_MODIFIED, name => '$sub' } )
                  unless defined $sub;

                BEGIN {
                    $sub =
                      ::DISPATCH( $::Scalar, 'new',
                        { modified => $_MODIFIED, name => '$sub' } );
                }
                my $List__ =
                  ::DISPATCH( $::Array, 'new',
                    { modified => $_MODIFIED, name => '$List__' } );
                my $self;
                $self =
                  ::DISPATCH( $::Scalar, 'new',
                    { modified => $_MODIFIED, name => '$self' } )
                  unless defined $self;

                BEGIN {
                    $self =
                      ::DISPATCH( $::Scalar, 'new',
                        { modified => $_MODIFIED, name => '$self' } );
                }
                $self = shift;
                $List__->{_value}{_array} = \@_;
                ::DISPATCH(
                    $GLOBAL::Code_say,
                    'APPLY',
                    ::DISPATCH(
                        $::Str, 'new', 'oops - multis not implemented yet'
                    )
                );
                $candidates;
                $sub;
                do {
                    for my $sub (
                        @{ ::DISPATCH(
                                $Code_prefix_58__60__64__62_,
                                'APPLY',
                                ::DISPATCH(
                                    $GLOBAL::Code_prefix_58__60__64__62_,
                                    'APPLY',
                                    ::DISPATCH( $self, "long_names" )
                                )
                              )->{_value}{_array}
                        }
                      )
                    {
                        do {
                            if (
                                ::DISPATCH(
                                    ::DISPATCH(
                                        ::DISPATCH(
                                            $GLOBAL::Code_infix_58__60__61__61__62_,
                                            'APPLY',
                                            ::DISPATCH(
                                                ::DISPATCH(
                                                    $sub, 'signature',
                                                ),
                                                'arity',
                                            ),
                                            ::DISPATCH(
                                                ::DISPATCH(
                                                    ::DISPATCH(
                                                        $List__, 'INDEX',
                                                        ::DISPATCH(
                                                            $::Int, 'new',
                                                            0
                                                        )
                                                    ),
                                                    'signature',
                                                ),
                                                'arity',
                                            )
                                        ),
                                        "true"
                                    ),
                                    "p5landish"
                                )
                              )
                            {
                                ::DISPATCH(
                                    $GLOBAL::Code_push,
                                    'APPLY',
                                    ::DISPATCH(
                                        $GLOBAL::Code_prefix_58__60__64__62_,
                                        'APPLY', $candidates
                                    ),
                                    $sub
                                );
                            }
                          }
                    }
                };
                ::DISPATCH(
                    $GLOBAL::Code_say,
                    'APPLY',
                    ::DISPATCH( $candidates, 'elems', ),
                    ::DISPATCH( $::Str, 'new', ' subs matched the arity' )
                );
            }
        )
    );
    1
}

