=head1 Ambient subs

=head2 slurp

    multi slurp (Str $filename, Bool :$bin, Str :$enc --> Str|Buf)

Reads the file with the name C<$filename>, and returns a single C<Str> or
C<Buf> with all the contents. Takes an optional named parameter C<$bin>,
C<False> by default, signifying whether to treat the file as a binary file
rather than as a text file. (XXX: What does this mean, exactly?) Also takes
a named parameter C<$enc> specifying the encoding, with default "Unicode".

If the file cannot be opened or read for some reason, C<slurp> will throw
an exception.

=head2 length

This is no longer a sub in Perl 6. Use C<chars> to count the number of
characters in a C<Str>, or C<elems> for the number of elements in a C<List>.
