=head1 Constants

=head2 True

Short for C<Bool::True>, an enum value exported from the enum C<Bool>.
Represents logical truth, the value yielded, for example, by successful
comparisons.

=head2 False

Short for C<Bool::False>, an enum value exported from the enum C<Bool>.
Represents logical truth, the value yielded, for example, by failed
comparisons.
