=head1 Declaration keywords

=head2 subset

Declares a subtype of a type, a collection of instances of that type
which adhere to a given condition.

 my subset Positive of Num where { $^n > 0 };
 my Positive $p;
 $p = 10;   # WORKS
 $p = -42;  $ FAILS

This subtype can then be referred to anywhere an ordinary class or role can.

The condition block will want to check the instance for some relation being
upheld. The instance can be referred to in the following three ways:

    { $_ > 0 }          # as the topic variable $_
    -> $n { $n > 0 }    # as an explicit names parameter
    { $^n > 0 }         # as a placeholder parameter

You cannot instantiate subtypes. In other words, this doesn't work:

 my Positive $p .= new;

To export a subset type, put the export trait just before the C<where>:

    subset DNA of Str is export where { all(.comb) eq 'A'|'C'|'G'|'T' };
