=head1 Sigils

=head2 C<$>

tbd

=head2 C<@>

Indicates a variable which adheres to the C<Positional> role.

 my @planets = <Mercury Venus Earth Mars Jupiter Saturn Uranus Neptune>;

The contract induced by the C<Positional> role means that you can expect
to do C<postcircumfix:<[ ]>> on objects doing that role.

Common examples of classes doing the C<Positional> role are C<List> and
C<Array>. C<Match> objects also do C<Positional>.

=head2 C<%>

tbd
