=head1 Twigils

=head2 C<^>

=for STD twigil:sym<^>

Variables with the C<^> L<twigil> are considered positional parameters of the
current block. If multiple variables with such a twigil appear within the
same block, they are matched up with arguments in the lexicographic order of
their names. For example:

    { say "$^b $^a $^c" }.(1, 2, 3)   # prints '2 1 3'

It is illegal to use self-declared parameters inside a block that already has
an explicit signature, or that is the body of a L<routine>.

The C<^> twigil is required only at the first occurrence of the
variable, so you can write

    @list.sort: { $^b <=> $^a - $b }

Both C<$^b> and C<$b> refer to the second positional parameter of that block.

