=head1 NAME

Perl6::Doc -- Table of Contents for Perl 6 Documentation

=head1 DESCRIPTION

This table of contents briefly lists each of the documents available as
part of the Perl 6 documentation system.

=head2 Starting points

    Doc                This table of contents
    Intro              A brief introduction for new Perl users

=head2 Overview

    Overview::Syntax       General syntax
    Overview::Functions    Built-in functions
    Overview::Operators    Built-in operators

=head2 Tutorials

=head2 FAQ

=head2 Language Specification

=head2 Core API

=head2 Perl 5 topics

    Perl5::Docfinder        Table of equivalences between Perl 5 and 6 docs
    Perl5::Differences      Differences between Perl 5 and 6

=head1 AUTHOR

Kirrily "Skud" Robert, <skud@cpan.org>
