=head1 NAME

Perl6::Doc::Reference -- Perl 6 language reference

=head1 DESCRIPTION

This section of the Perl 6 documentation is a general-purpose language
reference.  For details of available documents within this area, see
L<Perl6::Doc::TOC>.

=head1 AUTHOR

Kirrily "Skud" Robert, <skud@cpan.org>
