#!/bin/sh

# This script is used by feather for auto-smoke.
# http://perlcabal.org/smoke.html is generated
# by this script, and http://perlcabal.org/syn
# also needs it.

# virtual mem: 1 GB
ulimit -v $(( 1 * 10 ** 6 ))
# cup-time: 5 hours
ulimit -t $(( 5 * 3600 ))

cd /home/agentzh/svn-pugs
svn up

PATH=/usr/local/bin:$PATH
echo "[auto-smoke] * Using GHC at" `which ghc`

nice -n5 perl Makefile.PL
HARNESS_PUGS=util/limited_pugs nice -n5 make smoke

cp smoke.yml ..
cp smoke.html ..

