#!/bin/sh

# This script is used by feather for auto-smoke.
# http://perlcabal.org/smoke.html is generated
# by this script, and http://perlcabal.org/syn
# also needs it.

# virtual mem: 1.5 GB
ulimit -v 1500000
# cup-time: 5 hours
ulimit -t 18000

cd /home/agentzh/svn-pugs
svn up

PATH=/usr/local/bin:$PATH
perl Makefile.PL
HARNESS_PUGS=util/limited_pugs nice -n5 make smoke

cp smoke.yml ..
cp smoke.html ..

