#!/bin/sh

# This script is used by feather's cron to update
# the Synopsis pages in http://perlcabal.org/syn/

# virtual mem: 1 GB
ulimit -v $(( 1 * 10 ** 6 ))
# cpu-time: 10 min
ulimit -t $(( 10 * 60 ))

ROOT_DIR=/home/agentzh
DEST_DIR=$ROOT_DIR/syn
SVN_DIR=$ROOT_DIR/svn-pugs
POD_DIR="$SVN_DIR/docs/Perl6/Spec"

cd $SVN_DIR
svn up

perl util/smartlinks.pl --out-dir $DEST_DIR --dir $ROOT_DIR/svn-pugs/t --css /syn/perl.css --line-anchor --pod-dir $POD_DIR
perl util/smartlinks.pl --out-dir $DEST_DIR/S32 --pod-dir $POD_DIR/S32-setting-library --dir t --css /syn/perl.css --line-anchor

# Copy the icons for smartlinks highlighting
cp -ufp docs/feather/hilite-*.png $DEST_DIR/
# And the css file
cp -ufp docs/feather/perl.css     $DEST_DIR/

perl util/podhtm.pl --url-prefix http://feather.perl6.nl/syn/ --url-postfix .html --index --charset=UTF-8 --out $DEST_DIR/Differences.html docs/Perl6/Perl5/Differences.pod

# Probably outdated, builds the Chinese version of Syn 1
cd $DEST_DIR/zh-cn
make

