#! /usr/bin/perl

use strict;
use warnings;

use Cwd;

my $KP6DIR=cwd;

my $PROG  = $ARGV[0];
my $KP6="perl -I${KP6DIR}/../v6-MiniPerl6/lib5 -I${KP6DIR}/lib5 ${KP6DIR}/kp6-perl5.pl --perl5rx";

if ($PROG and -e $PROG)
{
    my $PROGC = "${PROG}.compiled";
    my $t_PROG  = (stat($PROG))[9];
    my $t_PROGC = (stat($PROGC))[9];

    if ( ! -e $PROGC or $t_PROG > $t_PROGC ) { # cache pre-compile
        system("$KP6 < $PROG | perltidy > $PROGC");
    }
    system("perl -I${KP6DIR}/lib5 $PROGC");
}
else
{
    my $cmd = "$KP6 | perl -I${KP6DIR}/lib5";
    system($cmd);
}

