#! /usr/bin/perl

use strict;
use warnings;

use Cwd;

my $KP6DIR=cwd;

my $PROG  = $ARGV[0];
my $KP6="perl -I${KP6DIR}/../v6-MiniPerl6/lib5 -I${KP6DIR}/lib-kp6-mp6-p5 ${KP6DIR}/kp6-perl5.pl ";

if ($PROG and -e $PROG)
{
    system("$KP6 < $PROG | perl -I${KP6DIR}/lib-modules-p5 -I${KP6DIR}/lib-kp6-mp6-p5") and die "Could not compile/run $PROG";
}
else
{
    my $cmd = "$KP6 | perl -I${KP6DIR}/lib5";
    system($cmd);
}

