default: all

all:
	aclocal
	autoheader
	automake --add-missing
	autoconf

clean:
	rm -f configure
	rm -f config.sub
	rm -f config.guess
	rm -f Makefile.in
	rm -f config.h.in
	rm -rf autom4te.cache
	rm -f stamp-h.in
	rm -f aclocal.m4
	rm -f missing
	rm -f install-sh
	rm -f depcomp
	rm -f src/Makefile.in
	rm -f include/Makefile.in
	rm -f test/Makefile.in

build-world:
	make -f Makefile.cvs
	./configure
	make test

clean-world:
	make distclean
	make -f Makefile.cvs clean