#!/usr/bin/perl
# Update the ir_nodes_report.output directory.
use strict;
use warnings;

require 'ir_nodes.pl';
our @nodes = IR_Zero_Def::nodes();

my $dir = "ir_nodes_report.output";
die "You need to create a directory $dir for the output.\n" if !-d $dir;

sub node_names {map{$_->name} @nodes;}
sub field_names {map{map{$_->name} $_->fields} @nodes;}

sub _save {
    my($open_spec,@lines)=@_;
    open(F,$open_spec) or die $!;
    print F join("\n",@lines,"");
    close(F);
}

_save(">$dir/node_names",
      node_names);

_save(">$dir/node_names.sorted",
      sort(node_names()));

# unix sort nicely places $.foo and @.foo together.
_save("| sort > $dir/field_names",
      field_names);

print "$dir updated.\n";
