=head1 NAME

Duration::Gregorian - durations relative to the Gregorian Calendar

=head1 SYNOPSIS

 # note: normally you get a Duration::Gregorian like this:
 use Date::Gregorian;
 my $duration = date("2001") - "2000";
 say $duration;   # "2000/P1Y" - ISO-8601 duration format

 # you can, however, explicitly create them like this:
 use Duration::Gregorian;
 my $duration = Duration::Gregorian.new("P1Y");# ISO-8601
 $duration = duration "P3Y1M3DT6H2M4S";  # ISO-8601

 $duration = duration "3Y 1M 3D 6h 2m 4s";
 $duration = duration $secs;  # secs

=head1 DESCRTIPTION

B<Duration::Gregorian> represents durations against the Gregorian
calendar as Perl 6 objects.

You can use the C<+>, C<->, C<E<lt>> and C<E<gt>> operators as with
native perl data types to manipulate these values, as well as add them
to C<Date::Gregorian> based objects.

=head2 Overview

B<Duration::Gregorian> operations are divided into three broad
categories:

=over

=item *

Creating new B<Duration::Gregorian> objects

=item *

Performing arithmetic with B<Duration::Gregorian> objects, and
possibly B<Date> objects, particularly B<Date::Gregorian>.

=item *

Extracting out parts of B<Duration::Gregorian> objects, and expressing
them as a single number of homogenous units.

=back

=cut

