/* This is autogenerated coded */
#include <stdio.h>
#include <smop.h>
#include <smop_s1p.h>
#include <smop_lowlevel.h>



int main(int argc, char** argv) {
  smop_init();

  SMOP__Object* interpreter = SMOP_DISPATCH(SMOP__INTPTR__InterpreterInstance, SMOP_RI(SMOP__INTPTR__InterpreterInstance),
                                            SMOP__ID__new, 
                                            SMOP__NATIVE__capture_create(SMOP__INTPTR__InterpreterInstance,
                                                                         SMOP__INTPTR__InterpreterInstance,NULL,NULL));
  SMOP__Object* node = NULL;
  SMOP__Object* mold = 
SMOP__Mold_create(3,(SMOP__Object*[]) {SMOP_REFERENCE(interpreter,SMOP__S1P__RootNamespace),SMOP__NATIVE__idconst_createn("postcircumfix:{ }",17),SMOP__NATIVE__idconst_createn("$*OUT",5),SMOP__NATIVE__idconst_createn("FETCH",5),SMOP__NATIVE__idconst_createn("print",5),SMOP__NATIVE__idconst_createn("hello world\n",13),NULL},21,(int[]) {1,10,4,5,1,6,0,1,11,10,7,0,0,1,12,11,8,1,9,0,0})
  ;

  SMOP__Object* frame = SMOP__Mold__Frame_create(interpreter,mold);

  SMOP_DISPATCH(interpreter, SMOP_RI(interpreter),
                SMOP__ID__goto,
                frame);

  SMOP_DISPATCH(interpreter, SMOP_RI(interpreter),
                SMOP__ID__loop, SMOP__NATIVE__capture_create(interpreter,
                                                             SMOP_REFERENCE(interpreter,interpreter),
                                                             NULL, NULL));


  SMOP_RELEASE(SMOP__INTPTR__InterpreterInstance,interpreter);

  smop_destr();

  return 0;
}
