#!/bin/sh

cd smartlinks_data
rm -rf expected
cp -rT got expected
rm -rf got
cd ..

tar cvf smartlinks_data.tar smartlinks_data
gzip --best smartlinks_data.tar
# upload smartlinks_data.tar.gz to ~agentzh/public_html on feather

