=pod

=head1 NAME

10,000 ft view of the Perl6 MetaModel

=head1 NOTATIONAL CONVENTIONS

    i(Foo)     - instance of Foo
    Foo        - the user-level Foo class
    class(Foo) - the instance of Perl6::Class named "Foo"
    meta(Foo)  - the instance of Perl6::MetaClass which describes Foo

=head1 DESCRIPTION

Here is the basic layout of the metamodel (in ASCII art):


                +---------------+        
                | i(Foo)        |
                +---------------+
                | class         |------+
                | instance_data |      |
                +---------------+      |
                                       | <lookup by name>
                      ___              |
                     (   )             |
      +-------------( Foo ) *----------+
      |              (___)   
      |   
      |           <user level>
  ....|.........................................................
      |           <meta level>      
      |   
      |         +---------------+        
      +-------->| class(Foo)    |
                +---------------+
      +---------| meta          |
      |         | name          |
      |         +---------------+
      |     
      |         +---------------+        
      +-------->| meta(Foo)     |
                +---------------+
                | name          |
                | version       |
                | authority     |
                | %methods      |
                | %attributes   |
                +---------------+      
                                

=head1 FAQ

=head2 How do I get to C<Foo> if I've got a C<i(Foo)>?

Calling C<.ref> on an instance of C<Foo> (C<i(Foo)>) will get you C<Foo>.

=head2 How do I get to C<class(Foo)> if I've got C<Foo>?

C<Foo> is just a proxy to the metalevel C<class(Foo)> -- the interpreter
handles it, but it has no actual concrete form. Larry wants the class to be
really a thin layer which connects the meta and user worlds.

=head2 How do I get to C<meta(Foo)> if I've got a C<i(Foo)>?

Calling C<.meta> on an instance of C<Foo> will get you C<meta(Foo)>.

=head2 What is C<meta(Foo)> an instance of?

C<meta(Foo)> is an instance of C<MetaClass>. C<meta(MetaClass)> is again an
instance an instance of C<MetaClass>.

I.e. C<class(meta(MetaClass)) = class(meta(class(meta(Foo)))) = MetaClass>.

=head2 What about anonymous classes?

They're basically the same as named classes.

=head1 BOOTSTRAPPING ORDER

- Perl6::Object is loaded (in Perl6::MetaModel)
    - Perl6::MetaClass::new() is called for Perl6::Object *
        - Perl6::MetaClass::_build_meta() is called to create the meta(Perl6::MetaClass) *
            - Perl6::MetaClass::new() is called for Perl6::MetaClass *
            


* special case handling

=head1 AUTHORS

Stevan Little E<lt>stevan@iinteractive.comE<gt>

=cut
