#!/usr/local/bin/perl

use warnings;
use strict;

$| = 1;

use lib '../lib';
#use Perl6in5::Interpreter;
#my $runner = make_runner( 'Perl6in5::Grammar::STD_hand', $ARGV[0] );

use Perl6in5::Grammar::STD_hand;
use File::Slurp;

# don't parse by lines, pass the whole input string to the parser file.
my @data = ($ARGV[0])?(read_file($ARGV[0]) or die 'reading input file failed'):(join('',(<>)));

my $reader = sub { return shift @data };
my $runner = make_parser($reader) or die 'parser generation failed: '.$!;

my $result = $runner->();
exit $result;
