# DO NOT EDIT THIS FILE.
#
# This file is generated automatically from
# include/parrot/interpreter.h by config/gen/parrot_include.pl
#
# Any changes made here will be lost.
#
.constant IGLOBALS_CLASSNAME_HASH	0
.constant IGLOBALS_COMPREG_HASH	1
.constant IGLOBALS_ARGV_LIST	2
.constant IGLOBALS_NCI_FUNCS	3
.constant IGLOBALS_INTERPRETER	4
.constant IGLOBALS_DYN_LIBS	5
.constant IGLOBALS_CONFIG_HASH	6
.constant IGLOBALS_SIZE	7
