#!/usr/bin/perl

use strict;
use warnings;
use feature 'say';
use Carp;
use File::Copy;

my $STD = q{../../src/perl6};
my $P6VIM = q{../../util};
my $status;

sub safe_copy {
    my ($file,$to_file) = @_;

    copy($file, $to_file)
        or croak "Could not copy $file";
}

say "\n--Running 'svn update'";
$status = system('cd ../..; svn update'); 
die "Could not svn update pugs\n" if $status != 0;

say "\n--Running 'make clean all' for STD.pm";
$status = system('cd ../../src/perl6; make clean all'); 
die "Could not make STD.pm\n" if $status != 0;

say 'Building and copying STD.pm files';
safe_copy("$STD/Cursor.pmc",'lib/');
safe_copy("$STD/LazyMap.pm", 'lib/LazyMap.pmc');
safe_copy("$STD/STD.pmc", 'lib/');
safe_copy("$STD/CORE.pad", 'lib/');

