=head1 NAME

Perl6::Pugs::00Apocrypha - The Pugs Apocrypha

=head1 ABSTRACT

This document defines the format, intent and purpose for the Pugs Apocrypha
(PA) documents - the descriptions and plans for the design of Pugs.

=head1 DESCRIPTION

=head1 COPYRIGHT

Copyright 2005 by Autrijus Tang E<lt>autrijus@autrijus.orgE<gt>.

This document is free documentation; you can redistribute it and/or
modify it under the same terms as Pugs itself.

=cut
