#!/usr/bin/perl

use strict;
use warnings;

my $platform = shift;

use Cwd;
my $top = getcwd;

while (not -f "$top/util/fudge") {
    die "Not inside appropriate directory\n" unless $top;
    $top =~ s!(.*)/(.*)!!;
}

print join(' ',
    map {
        my $pick;
        if ( $_ !~ m/\.$platform$/ ) {
            chomp( $pick = `$^X $top/util/fudge $platform $_` );
        }
        defined $pick ? $pick : ();
    } @ARGV
), "\n";


