#!/usr/bin/perl

use strict;
use warnings;

my $platform = shift;
@ARGV = <@ARGV> if $^O eq 'MSWin32';

use Cwd;
my $top = getcwd;

while (not -f "$top/util/fudge") {
    die "Not inside appropriate directory\n" unless $top;
    $top =~ s!(.*)/(.*)!!;
}

print join(' ',
    map {
	chomp(my $pick = `$^X $top/util/fudge $platform $_`);
	$pick;
    } @ARGV
), "\n";
