#!/bin/sh

# to use this script, run the following command:
#   HARNESS_PUGS=util/limited_pugs make smoke

# virtual mem: 800 MB
ulimit -v 800000
# cpu time: 10 min
ulimit -t 600

nice -n5 ./pugs "$@"

