#!/usr/bin/perl
use strict;
use warnings;
use v5.10;
use lib 'src';
use AST;
use Gtk2 -init;
use lib '/home/pawel/Forest-Gtk2/lib';
use Forest::Gtk2;
use KiokuDB;
use Types;
my $dir = KiokuDB->connect('bdb:dir=profile');
my $s = $dir->new_scope;
my $uid = <>;
chomp($uid);
$Mildew::took = {
};
my @stack;
while (<>) {
    my ($c,$id,$secs,$nano) = /^(\w)(\d+):(\d+):(\d+)$/;
    if ($c eq 'e') {
        my $t = ($secs + ($nano / 1000_000_000)) - pop (@stack);
        #say "$id took $t";
        $Mildew::took->{$id} +=  $t;
    } elsif ($c eq 's') {
        push @stack,($secs + ($nano / 1000_000_000));
    }
    #e0:1944:749773454
}
#use Data::Dumper;
#print Dumper($Mildew::took);


my $tree_view = Forest::Gtk2::tree_to_tree_view($dir->lookup($uid)->forest); 
my $window = Gtk2::Window->new('toplevel');
$window->add($tree_view);
$window->show_all;
Gtk2->main;

