#!/usr/bin/perl
use warnings;
use strict;
use IPC::Open2;
my $name;
my $m0ld;
while (<>) {
    if (/^\[(\w+)/) {
        spit_out($name,$m0ld) if defined $name;
        $m0ld = '';
        $name = $1;
    } else {
        $m0ld .= $_
    }
}
spit_out($name,$m0ld);

sub spit_out {
    my ($name,$m0ld) = @_;
    my ($writer, $reader);
    my $pid = open2($reader,$writer,"../smop/m0ld_exe --js") || die "$@";
    print $writer $m0ld;
    close($writer);
    local $/ = '';
    my $out = <$reader>;
    print "var $name = ",$out,";";
}
