#!/usr/bin/perl
# Update kp6_ast.info directory.
use strict;
use warnings;

require 'kp6_ast_def.pl';
our @nodes = KP6_AST_Def::nodes();

my $dir = "kp6_ast_def.info";
die "Directory ~/$dir required" if !-d $dir;

sub node_names {map{$_->name} @nodes;}
sub field_names {map{map{$_->name} $_->fields} @nodes;}

sub _save {
    my($open_spec,@lines)=@_;
    open(F,$open_spec) or die $!;
    print F join("\n",@lines,"");
    close(F);
}

_save(">$dir/node_names",
      node_names);

_save(">$dir/node_names.sorted",
      sort(node_names()));

# unix sort nicely places $.foo and @.foo together.
_save("| sort > $dir/field_names",
      field_names);

print "$dir updated.\n";
