#!/usr/bin/perl

use strict;
use Env qw(HOME USER);

print "Killing all instances of 'termserv.pl' for $USER\n";
system("killall --user $USER termserv.pl");
chdir "$ENV{HOME}/runpugs/bin";
print "Executing './termserv.pl' in the background\n";
system("(./termserv.pl > /dev/null &2>1)&");

