#!/bin/bash

perl util/compile_p6grammar.pl -D examples/adder.grammar > Adder.pm
perl -Ilib -MAdder -e 'undef $/;print Adder->add(<>)->()' examples/adder.input > trace.out
perl util/gen-tracer-view.pl --outdir tmp/adder examples/adder.grammar examples/adder.input < trace.out
echo

perl util/compile_p6grammar.pl -D examples/digits.grammar > Digits.pm
perl -Ilib -MDigits -e 'undef $/;print Digits->count(<>)->()' examples/digits.input > trace.out
perl util/gen-tracer-view.pl --outdir tmp/digits examples/digits.grammar examples/digits.input < trace.out
echo

perl util/compile_p6grammar.pl -D examples/langs.grammar > Langs.pm
perl -Ilib -MLangs -e 'undef $/;print My::VB->def(<>)->()' examples/langs.input > trace.out
perl util/gen-tracer-view.pl --outdir tmp/langs examples/langs.grammar examples/langs.input < trace.out
echo

perl util/compile_p6grammar.pl -D examples/langs2.grammar > Langs2.pm
perl -Ilib -MLangs2 -e 'undef $/;print My::VB->def(<>)->()' examples/langs.input > trace.out
perl util/gen-tracer-view.pl --outdir tmp/langs2 examples/langs2.grammar examples/langs.input < trace.out
echo

perl util/compile_p6grammar.pl -D examples/Grammar.grammar > Grammar.pm
perl -Ilib -MGrammar -e 'undef $/;print Pugs::Grammar::Rule->spec(<>)->()' examples/grammar.input > trace.out
perl util/gen-tracer-view.pl --outdir tmp/grammar examples/Grammar.grammar examples/grammar.input < trace.out
echo

scp -r -l 10000 -P 18888 tmp/* agentzh@agentzh.org:~/misc/tracer/

