$*OUT.FETCH.print("1..3\n");
$*inner = $SMOP__S1P__LexicalScope.new();
$*inner.FETCH.outer = $SMOP__S1P__LexicalScope.new();
$*inner.FETCH.outer.FETCH.outer = $SMOP__S1P__LexicalScope.new();
$*inner.FETCH.outer.FETCH.outer.FETCH.{'$a'} = $SMOP__S1P__Scalar.new();
$*inner.FETCH.outer.FETCH.outer.FETCH.{'$a'}.FETCH = "ok 1\n";
$*OUT.FETCH.print($*inner.FETCH.lookup('$a').FETCH.FETCH());
$*inner.FETCH.outer.FETCH.{'$a'} = $SMOP__S1P__Scalar.new();
$*inner.FETCH.outer.FETCH.{'$a'}.FETCH = "ok 2\n";
$*OUT.FETCH.print($*inner.FETCH.lookup('$a').FETCH.FETCH());
$*inner.FETCH.{'$a'} = $SMOP__S1P__Scalar.new();
$*inner.FETCH.{'$a'}.FETCH = "ok 3\n";
$*OUT.FETCH.print($*inner.FETCH.lookup('$a').FETCH.FETCH());
