#!/usr/bin/perl
use warnings;
use strict;
use Term::ANSIColor qw(:constants);
open(my $std,shift);

open(my $actions,shift);
my (%actions,$action);
for (<$actions>) {
    if (/^### (.*?)\s*$/) {
        $action = $1;
    } else {
        $actions{$action} .= $_;
    }
}

my ($name);
for (<$std>) {
    if (/(?:token|rule) ([\w:]+)/) {
        $name = $1;
#        warn YELLOW,"$name",RESET;
    }
    if (/\{\*\} \s* (?:\#=(.*))?/x) {
        my $tag = $1 || ""; 
        my $full_name = $name . $tag;
#        warn "inserting ".GREEN.$full_name.RESET if $actions{$full_name};
#        warn "not inserting <".RED.$full_name.RESET.">" unless $actions{$full_name};
        my $content = $actions{$full_name} // "*";
        chomp($content);
        s/\{\*\}/{$content}/;
    }
    print $_;
}
