#!/usr/bin/perl
use warnings;
use strict;
use Term::ANSIColor qw(:constants);
open(my $std,shift);

open(my $actions,shift);
my (%actions,$action);
for (<$actions>) {
    if (/^### (.*?)\s*$/) {
        $action = $1;
    } else {
        $actions{$action} .= $_;
    }
}

my ($name);
for (<$std>) {
    if (/(?:regex|rule|token) \s+ ([:\w]+?(?:sym<.*?>)?)\s/x) {
        $name = $1;
#        $name =~ s/:sym<(.*)>/$1/;
#        warn YELLOW,"$name",RESET;
    }
    if (/\{\*\} .*? (?:\#=(.*))?$/x) {
        my $tag = $1 || ""; 
        my $full_name = $name . $tag;
#        warn "inserting ".GREEN.$full_name.RESET."\n".$_ if $actions{$full_name};
#        warn "not inserting <".RED.$full_name.RESET.">" unless $actions{$full_name};
        my $content = $actions{$full_name} // "*";
        chomp($content);
        s/\{\*\}/{$content}/;
    }
    print $_;
}
