#!/usr/local/bin/perl

use Getopt::Long;
my $nocolor;
my $vertical;
my $yaml;
my $quiet;
BEGIN {
    GetOptions("nocolor"=>\$nocolor,"vertical"=>\$vertical,"quiet"=>\$quiet,"yaml"=>\$yaml);
    unless ($#ARGV <= 0) {
        die "USAGE: [--nocolor] [filename]\n";
    }
    if ($quiet) {
        $SIG{__WARN__} = sub {};
        open(STDERR,">/dev/null");
    }
}
#eval {
use lib '../../src/perl6';
use STD;
use ElfCore5;
use DumpMatch;
use utf8;
use YAML::XS;
use Encode;
require 'mangle.pl'; 
sub ::unmangle {
    local $_ = shift;
    s/Grave/\`/g;
    s/Tilde/\~/g;
    s/Bang/\!/g;
    s/At/\@/g;
    s/Sharp/\#/g;
    s/Dollar/\$/g;
    s/Percent/\%/g;
    s/Caret/\^/g;
    s/Amp/\&/g;
    s/Star/\*/g;
    s/Paren/\(/g;
    s/Thesis/\)/g;
    s/Minus/\-/g;
    s/Plus/\+/g;
    s/Equal/\=/g;
    s/Cur/\{/g;
    s/Ly/\}/g;
    s/Bra/\[/g;
    s/Ket/\]/g;
    s/Vert/\|/g;
    s/Back/\\/g;
    s/Colon/\:/g;
    s/Semi/\;/g;
    s/Single/\'/g;
    s/Double/\"/g;
    s/Lt/\</g;
    s/Gt/\>/g;
    s/Fre/\«/g;
    s/Nch/\»/g;
    s/Comma/\,/g;
    s/Dot/\./g;
    s/Question/\?/g;
    s/Slash/\//g;
    return $_;
#	s/(\W)/sprintf("_%02x_",ord($1))/eg;
}
sub ::vague {
    my ($name,) = @_;
    $name =~ s/_//g;
    $name =~ s/ //g;
    $name =~ s/:sym<(.*?)>/:$1/g;
    $name;
}
use strict;
use warnings;

if ($nocolor) {
    $DumpMatch::NOCOLOR = 1;
}

my $what = 'comp_unit';
my $text;
{
local $/;
$text = Encode::decode('utf8', scalar <>);
}

open(my $actions,"pixie_actions5") || die "can't open actions file:$!";
my (%actions,$action);
for (<$actions>) {
    if (/^### (.*?)\s*$/) {
        $action = $1;
    } else {
        $actions{::vague($action)} .= $_;
    }
}

while (my ($name,$code) = each %actions) {
    my $str = qq!sub {\npackage pixie_actions;\n#line 1 "action $name"\n!.$code."}";
        #print $str;
    $actions{$name} = eval($str);
    die "error at pixie_action5, action $name: $@\n" if $@;
}
#use Data::Dump::Streamer;
#print Dump(\%actions);


{ package pixie_actions;
    sub make($) {
        $_->{''} = $_[0];
    }
    sub EXPR {
        my $expr = shift;
        use Data::Dumper;
        if ($expr->{pre} && @{$expr->{pre}}) {
            IRx1::Apply->new(
                function => 'prefix:'.$expr->{pre}[0]->item,
                capture  => IRx1::Capture->new(arguments=>[$expr->{noun}->item]),
            );
        } elsif ($expr->{post} && @{$expr->{post}}) {
            IRx1::Apply->new(
                function => 'postfix:'.$expr->{post}[0]->item,
                capture  => IRx1::Capture->new(arguments=>[$expr->{noun}->item]),
            );
        } elsif ($expr->{noun}) {
            $expr->{noun}->item;
        } elsif ($expr->{infix}) {
            IRx1::Apply->new(
                function => 'infix:'.$expr->{infix}->item,
                capture  => IRx1::Capture->new(arguments=>[EXPR($expr->{left}),EXPR($expr->{right})]),
            );
        } else {
            warn 'unknown EXPR type';
            undef;
        }
    }
    sub quote {
        my $quote = shift;

        my $nibble = $quote->{nibble};
        return IRx1::Buf->new(buf=>'') unless $nibble;

        my @parts;
        my @escapes =  sort {print "$a:$b";$a->from cmp $b->from} @{$nibble->{escape} // []};
        use Term::ANSIColor qw(:constants);
        my $at = $nibble->from;

        for my $escape (@escapes) {
            my $str = substr(${$nibble->orig},$at,$escape->from-$at);
            push(@parts,IRx1::Buf->new(buf=>$str)) if $str;
            push(@parts,$escape->{variable}->item);
            $at = $escape->to;
        }
        push(@parts,IRx1::Buf->new(buf=>substr(${$nibble->orig},$at,$nibble->to-$at)));
        my $item = shift @parts;
        for (@parts) {
            $item = IRx1::Apply->new(function=>'infix:~',capture=>IRx1::Capture->new(arguments=>[$item,$_]));
        }
        return $item;
    }
}
{ package Perl_with_actions;
    use Term::ANSIColor qw(:constants);
    BEGIN { our @ISA = qw(Perl) }
    sub _REDUCE {
        my $self = shift;
        my $tag = shift;
        $tag =~ s/__S_\d+/:/;
        my $tag = ::unmangle($tag);

        if ($actions{::vague($tag)}) {
            print (GREEN,$tag,RESET,"\n") unless $quiet;
            local $_ = $self;
            $actions{::vague($tag)}->();
            $self;
        } else {
            print (RED,$tag," ~~ ",::vague($tag),RESET,"\n") unless $quiet;
            $self;
        }
    }
}

use Data::Dumper;
print Dumper(\%actions);
my $r = Perl_with_actions->new($text)->$what();
if ($yaml) {
    print Dump($r);
    exit;
} else {
    print dump_match($what=>$r,{vertical=>1,mark_arrays=>1,actions=>sub {Compiler::dump_IRx1(@_)}}),"\n" unless $quiet;
}
my $ir = $r->{''};
my $code = $GLOBAL::compiler1->emitter->prelude_lexical . $ir->callback($GLOBAL::compiler1->emitter);
print $GLOBAL::compiler1->emitter->tidy($code),"\n" unless $quiet;
eval($code);
print "error: $@" if $@;
#};
#if ($@) {
#    print "fatal error: $@";
#    die;
#}

