=encoding utf8

=head1 TITLE

Synopsis 29: Functions

=head1 AUTHOR

Rod Adams <rod@rodadams.net>

=head1 VERSION

  Maintainer: Larry Wall <larry@wall.org>

=head1 Placeholder

This pod is just a placeholder for the draft of Synopsis 29 that
currently lives at

    http://svn.openfoundry.org/pugs/docs/Perl6/Spec/Functions.pod

=for vim:set expandtab sw=4:
