=pod

=encoding utf8

=head1 NAME

Rosetta::FAQ -
Answers to your questions

=head1 DESCRIPTION

This document is a place for you to write in questions you have about the
Rosetta DBMS framework, such as when you don't understand a feature or want
to know how to accomplish a task with it.  Answers will be written in below
your questions later, or the other Rosetta documentation files updated to
cover it and your question removed, as is appropriate.

Alternately, you can write in both questions and answers that you think are
correct, where you think they would be commonly asked.  Feel free to create
multiple sections below, rather than just QUESTIONS AND ANSWERS.

=head1 QUESTIONS AND ANSWERS

Q.

A.

Q.

A.

...

=head1 SEE ALSO

Go to L<Rosetta> for the majority of distribution-internal references, and
L<Rosetta::SeeAlso> for the majority of distribution-external references.

=head1 AUTHOR

Darren R. Duncan (C<perl@DarrenDuncan.net>)

=head1 LICENCE AND COPYRIGHT

This file is part of the Rosetta DBMS framework.

Rosetta is Copyright (c) 2002-2006, Darren R. Duncan.

See the LICENCE AND COPYRIGHT of L<Rosetta> for details.

=head1 ACKNOWLEDGEMENTS

The ACKNOWLEDGEMENTS in L<Rosetta> apply to this file too.

=cut
