=head1 NAME

Perl6::Doc::Perl5::Docfinder -- Where to find the equivalent of Perl 5 docs

=head1 DESCRIPTION

The docs have moved around lots, so here's a cheat-sheet of what's
where.  

    perldelta       Perl6::Doc::Perl5::Differences (sort of)
    perlintro       Perl6::Doc::Intro
    perltoc         Perl6::Doc::TOC

=head1 AUTHOR

Kirrily "Skud" Robert, <skud@cpan.org>
