default: all

all:
	aclocal
	autoheader
	automake --add-missing
	autoconf

clean:
	rm -f configure
	rm -f Makefile.in
	rm -f config.h.in
	rm -rf autom4te.cache
	rm -f stamp-h.in
	rm -f aclocal.m4
	rm missing
	rm install-sh
	rm depcomp
	rm -f src/Makefile.in
