=pod

=encoding utf8

=head1 NAME

Muldis::DB::Language::Ext::Temporal -
Muldis D extension for temporal data types and operators

=head1 VERSION

This document is Muldis::DB::Language::Ext::Temporal version 0.1.0.

=head1 PREFACE

This document is part of the Muldis D language specification, whose root
document is L<Muldis::DB::Language>; you should read that root document
before you read this one, which provides subservient details.

=head1 DESCRIPTION

Muldis D has a mandatory core set of system-defined (eternally available)
entities, which is referred to as the I<Muldis D core> or the I<core>; they
are the minimal entities that all Muldis D implementations need to provide;
they are mutually self-describing and are used to bootstrap the language;
any entities outside the core, called I<Muldis D extensions>, are
non-mandatory and are defined in terms of the core or each other, but the
reverse isn't true.

This current C<Temporal> document describes the system-defined I<Muldis D
Temporal Extension>, which consists of temporal data types and operators,
particularly durations and dates or times.

This current document does not describe the polymorphic operators that all
types, or some types including core types, have defined over them; said
operators are defined once for all types in L<Muldis::DB::Language::Core>.

I<This documentation is pending.>

=head1 TYPE SUMMARY

Following are all the data types described in this document, arranged in a
type graph according to their proper sub|supertype relationships (but that
the first 4 just reappear from the core set to provide a similar context,
and aren't re-described here):

    sys.type.Universal

        sys.type.Empty

        sys.type.Scalar
            sys.type.Ordinal

                # The following are all regular ordinal scalar types.

                sys.type.Temporal.Duration
                sys.type.Temporal.DurationOfDays
                sys.type.Temporal.DateTime
                sys.type.Temporal.DateTimeNoTZ
                sys.type.Temporal.Date
                sys.type.Temporal.DateNoTZ
                sys.type.Temporal.Time
                sys.type.Temporal.TimeNoTZ

I<This documentation is pending.>

=head1 SYSTEM-DEFINED TEMPORAL SCALAR DATA TYPES

These non-core scalar data types describe common kinds of temporal
artifacts according to modern calendars.  They come in a variety of
precisions and epochs so that users can pick one that most accurately
represents what they actually know about their data.  I<Of course, dealing
with these types in general isn't a perfect science; they stand to be
revised or rewritten.>

=over

=item C<sys.type.Temporal.Duration>

A C<Temporal.Duration> is a single amount of time, with precision to
arbitrary fractions of a second.  It is not fixed to any date or time and
is agnostic to both the calendar and whether or not a time-zone offset is
known.  Its default value is zero.  The cardinality of this type is
infinity; to define a most-generalized finite C<Temporal.Duration> subtype,
you must specify the maximum amount of time that its values may be.

=item C<sys.type.Temporal.DurationOfDays>

A C<Temporal.DurationOfDays> is the same as C<Temporal.Duration> in all
respects but that its precision is only to the whole terrestrial day.  The
cardinality of this type is infinity; to define a most-generalized finite
C<Temporal.DurationOfDays> subtype, you must specify the maximum amount of
time that its values may be.

=item C<sys.type.Temporal.DateTime>

A C<Temporal.DateTime> is a single specific time on a specific date, with
precision to arbitrary fractions of a second.  It I<does> incorporate an
explicit terrestrial time-zone offset (relative to UTC), so you use it when
you I<do know> the time-zone and it is significant (which is usually).  It
is conceptually calendar-agnostic.  The default value of
C<Temporal.DateTime> is the Perl 6 epoch, namely 2000-1-1T0:0:0 in the
Gregorian calendar, with a time-zone offset of zero.  The cardinality of
this type is infinity; to define a most-generalized finite
C<Temporal.DateTime> subtype, you must specify the earliest and latest
datetimes it includes, and also its least magnitude fraction of a second.

=item C<sys.type.Temporal.DateTimeNoTZ>

A C<Temporal.DateTimeNoTZ> is the same as C<Temporal.DateTime> in its
precision, but it I<does not> incorporate an explicit terrestrial time-zone
offset interval, and so it is conceptually ambiguous within an interval of
about 25 hours; you use it when you I<do not know> the time-zone or it is
not significant (which is not usually).  Its default value is
2000-1-1T0:0:0 in the Gregorian calendar.  Matters of its cardinality are
the same as for C<Temporal.DateTime>.

=item C<sys.type.Temporal.Date>

A C<Temporal.Date> is the same as C<Temporal.DateTime> in all respects but
that its precision is only to the whole terrestrial day.  Its default value
is 2000-1-1 in the Gregorian calendar.  The cardinality of this type is
infinity; to define a most-generalized finite C<Temporal.Date> subtype, you
must specify the earliest and latest dates it includes.

=item C<sys.type.Temporal.DateNoTZ>

A C<Temporal.DateNoTZ> is the same as C<Temporal.Date> in all respects but
that its differences correspond to the differences between
C<Temporal.DateTime> and C<Temporal.DateTimeNoTZ>.  Matters of its
cardinality are the same as for C<Temporal.Date>.

=item C<sys.type.Temporal.Time>

A C<Temporal.Time> is a single specific time that isn't on any day in
particular, and isn't part of any calendar in particular, with a precision
to arbitrary fractions of a second; its allowed range is between zero
seconds (inclusive) and 1 terrestrial day (exclusive).  It does incorporate
an explicit time-zone offset interval as per C<Temporal.DateTime>.  Its
default value is 0:0:0.  The cardinality of this type is infinity; to
define a most-generalized finite C<Temporal.Time> subtype, you must specify
its least magnitude fraction of a second.

=item C<sys.type.Temporal.TimeNoTZ>

A C<Temporal.TimeNoTZ> is the same as C<Temporal.Time> in all respects but
that its differences correspond to the differences between
C<Temporal.DateTime> and C<Temporal.DateTimeNoTZ>.  Matters of its
cardinality are the same as for C<Temporal.Time>.

=back

=head1 SEE ALSO

Go to L<Muldis::DB> for the majority of distribution-internal references,
and L<Muldis::DB::SeeAlso> for the majority of distribution-external
references.

=head1 AUTHOR

Darren Duncan (C<perl@DarrenDuncan.net>)

=head1 LICENSE AND COPYRIGHT

This file is part of the Muldis::DB framework.

Muldis::DB is Copyright © 2002-2007, Darren Duncan.

See the LICENSE AND COPYRIGHT of L<Muldis::DB> for details.

=head1 ACKNOWLEDGEMENTS

The ACKNOWLEDGEMENTS in L<Muldis::DB> apply to this file too.

=cut
