=head1 Bootstrapping Contributors

resig
dalek
S03
feather
LTA
proto
rakudo *
spectests

What if a newbie to Perl 6 joined the Freenode IRC channel (as they are invited
to do by http://perl6.org) and tried to make sense of the discussion... with no
understanding of these terms? As it currently stands, there is no central
point-of-definition for any of these words.

Newbies must ask (which they are probably hesitant to do) if they
want to understand these terms and hence make sense of the discussion. Lurking
will provide understanding but this is no help to new contributors with limited
time (the vast majority?). 

We have a words/actions mismatch. By what we are saying on http://perl6.org,
we want to encourage the participation of newcomers, and yet little progress
has been made towards enabling that (though there are notable steps in the right
direction - perl6.org and the general friendliness of the channel's inhabitants
are but two examples).

#perl6 is the Agora and Forum of Perl 6 development, and it's currently
inaccessible to the general populace. The community should be better able to
access the central point of community self-reinvention.
