=head1 #perl6 lexicon

This is (the beginning of) a remedy-of-sorts to the problem posed
in "Bootstrapping Contributors".

Some abbreviations and acronyms are also explained as tooltips on
L<http://irclog.perlgeek.de/perl6/today>.

=head2 Terms

resig
  A branch on which Jonathan REworks SIGnature binding
  
dalek
  an IRC bot who reports commits to various source code repositories
  
S03
  "Synopsis 3". The L<Synopses|http://www.perlcabal.org/syn/> are the Perl 6
  specification.
  
feather
  A server for the Perl 6 development community. L<http://feather.perl6.nl/>.
  
LTA
  "Less Than Awesome". Perl 6 people tend to be positive, and so describe
  things with which they're not perfectly happy as "Less Than Awesome". If you
  doubt that first assertion, you haven't spent much time coding in Perl 6.
  It Makes You Happy (TM).
  
proto
  The beginnings of a solution to the problem of distributing Perl 6 modules.
  https://github.com/masak/proto/

rakudo *
  The planned release of Rakudo (a Perl 6 compiler targeting the Parrot VM) in
  Spring 2010.
  
spectests
  "Specification tests" - which a Perl 6 implementation must pass to be
  considered "Perl 6".
