#!/usr/bin/perl -w
use strict;

for my $ext (qw(hi o hi-boot o-boot)) {
    my @files=`find . -name \"*.$ext\"`;
    for my $f (@files) {
        chomp $f;
        system("rm -f $f");
    }
}
system("rm -f *~");
system("rm -f pugspc");

