translate: ASTTranslate.hs ASTDefinition.hs ASTParser.hs ASTUtil.hs
	ghc --make -o translate ASTTranslate.hs

sage: ASTTranslate-sage.hs ASTDefinition.hs ASTParser.hs ASTUtil.hs
	ghc --make -o translate ASTTranslate-sage.hs

clean: 
	-rm *.o *.hi
