#!/bin/sh
# AUTHORS
#
# The Pugs Team perl6-compiler@perl.org.
#
# SEE ALSO
#
# The Perl 6 homepage at http://dev.perl.org/perl6.
#
# The Pugs homepage at http://pugscode.org/.
#
# COPYRIGHT
#
# Copyright 2007 by Flavio Soibelmann Glock and others.
#
# This program is free software; you can redistribute it and/or modify it
# under the same terms as Perl itself.
#
# See http://www.perl.com/perl/misc/Artistic.html

cat - | KP6_TOKEN_DEBUGGER=1 perl script/kp6 2>/dev/null | perl -pi -e 's/(\>\>\>|\<\<\<|\-\-\-)/($1 eq ">>>") ? chr($::LEVEL + 65).("   " x $::LEVEL++) : $1 eq "<<<" ? chr(--$::LEVEL + 65).("   " x $::LEVEL ) : chr($::LEVEL + 65).("   " x $::LEVEL ) /ge' | less

